# Generated by Django 2.2 on 2021-02-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True, verbose_name='название категории')),
                ('slug', models.SlugField(max_length=70, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название статьи')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='краткое описание статьи')),
                ('posts_text', models.TextField(blank=True, verbose_name='текст статьи')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('like_quantity', models.PositiveIntegerField(default=0, verbose_name='кол-во')),
                ('is_active', models.BooleanField(default=False, verbose_name='активна')),
                ('comment', models.TextField(blank=True, verbose_name='комментарии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=70, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=70, verbose_name='URL')),
                ('text', models.TextField(verbose_name='комментировать')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата добавления')),
                ('moderation', models.BooleanField(default=False, verbose_name='модерация')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post', verbose_name='пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('created',),
            },
        ),
    ]
