# Generated by Django 3.1 on 2021-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210216_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='уникальный адрес'),
        ),
    ]
