# Generated by Django 3.1 on 2021-02-16 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210216_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 20, 17, 8, 37915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='xabruser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='статус персонала'),
        ),
    ]
