# Generated by Django 3.1.5 on 2021-02-19 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210216_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 23, 50, 35, 170197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='xabruser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='xabruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='xabruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен/неактивен'),
        ),
    ]
